Feature/results analysis rebased (#743)
* Adds telegraf support and setting oh hostnames

* Create AnsibleRunner()

Try to get past error:

http://uberjenkins.sc.couchbase.com/view/Performance/job/sync-gateway-perf-test/5/console

14:09:43 Traceback (most recent call last):
14:09:43   File "libraries/provision/provision_cluster.py", line 139, in <module>
14:09:43     sync_gateway_config=sync_gateway_conf
14:09:43   File "libraries/provision/provision_cluster.py", line 43, in provision_cluster
14:09:43     status = ansible_runner.run_ansible_playbook("set-hostnames.yml")
14:09:43 NameError: global name 'ansible_runner' is not defined
14:09:43 Build step 'Execute shell' marked build as failure

* Fix missing import

14:17:13 Traceback (most recent call last):
14:17:13   File "libraries/provision/provision_cluster.py", line 140, in <module>
14:17:13     sync_gateway_config=sync_gateway_conf
14:17:13   File "libraries/provision/provision_cluster.py", line 43, in provision_cluster
14:17:13     ansible_runner = AnsibleRunner(cluster_config)
14:17:13 NameError: global name 'AnsibleRunner' is not defined
14:17:13 Build step 'Execute shell' marked build as failure
14:17:13 Archiving artifacts
14:17:13 Finished: FAILURE

* Fix python syntax error

14:34:21 Starting performance tests
14:34:21 + python testsuites/syncgateway/performance/run_perf_test.py --test-id 2 --number-pullers 1000 --number-pushers 1000 --use-gateload --reset-sync-gw --sync-gateway-config-path resources/sync_gateway_configs/performance/sync_gateway_default_performance.json --doc-size 1024 --runtime-ms 2400000 --rampup-interval-ms 120000
14:34:21   File "testsuites/syncgateway/performance/run_perf_test.py", line 51
14:34:21     if use_loadgenerator == '--use-gateload'
14:34:21                                            ^
14:34:21 SyntaxError: invalid syntax
14:34:21 Build step 'Execute shell' marked build as failure
14:34:21 Archiving artifacts
14:34:21 Finished: FAILURE

* Fix param name

14:38:38 Starting performance tests
14:38:38 + python testsuites/syncgateway/performance/run_perf_test.py --test-id 2 --number-pullers 1000 --number-pushers 1000 --use-gateload --reset-sync-gw --sync-gateway-config-path resources/sync_gateway_configs/performance/sync_gateway_default_performance.json --doc-size 1024 --runtime-ms 2400000 --rampup-interval-ms 120000
14:38:39 Traceback (most recent call last):
14:38:39   File "testsuites/syncgateway/performance/run_perf_test.py", line 245, in <module>
14:38:39     rampup_interval_ms=opts.rampup_interval_ms,
14:38:39 TypeError: run_perf_test() got an unexpected keyword argument 'use_gateload'
14:38:39 Build step 'Execute shell' marked build as failure
14:38:39 Archiving artifacts
14:38:39 Finished: FAILURE

* Kick off sgload (WIP)

* Running sgload works

* Removed inactive plugin configuration sections

* Removed support for sgload as this is being handled in a new script

* Do not copy custom telegraf binary onto load generator hosts as gateload now pushes perf stats via statsd

* Add basic paramiko support

* Use argparse to propagate args down to sgload

also add concurrent.futures.ThreadPoolExecutor

* Discover sg url and pass on to sgload

* Debugging why sgload not working on jenkins

No output

* More debugging

* Unhardcode vagrant user

* Fix attempt for paramiko.transport:Unknown RequirementParseError error on jenkins

ERROR:paramiko.transport:Unknown exception: Invalid requirement RequirementParseError

18:21:19 {u'load_generators': [{u'ip': u's61904cnt72.sc.couchbase.com', u'name': u'lg1'}, {u'ip': u's61905cnt72.sc.couchbase.com', u'name': u'lg2'}], u'couchbase_servers': [{u'ip': u's61702cnt72.sc.couchbase.com', u'name': u'cb1'}, {u'ip': u's61703cnt72.sc.couchbase.com', u'name': u'cb2'}, {u'ip': u's61704cnt72.sc.couchbase.com', u'name': u'cb3'}], u'sync_gateways': [{u'ip': u's61705cnt72.sc.couchbase.com', u'name': u'sg1'}, {u'ip': u's61706cnt72.sc.couchbase.com', u'name': u'sg2'}], u'hosts': [{u'ip': u's61702cnt72.sc.couchbase.com', u'name': u'host1'}, {u'ip': u's61703cnt72.sc.couchbase.com', u'name': u'host2'}, {u'ip': u's61704cnt72.sc.couchbase.com', u'name': u'host3'}, {u'ip': u's61705cnt72.sc.couchbase.com', u'name': u'host4'}, {u'ip': u's61706cnt72.sc.couchbase.com', u'name': u'host5'}, {u'ip': u's61901cnt72.sc.couchbase.com', u'name': u'host6'}, {u'ip': u's61903cnt72.sc.couchbase.com', u'name': u'host7'}, {u'ip': u's61904cnt72.sc.couchbase.com', u'name': u'host8'}, {u'ip': u's61905cnt72.sc.couchbase.com', u'name': u'host9'}], u'load_balancers': [], u'sg_accels': [{u'ip': u's61901cnt72.sc.couchbase.com', u'name': u'ac1'}, {u'ip': u's61903cnt72.sc.couchbase.com', u'name': u'ac2'}]}
18:21:19 Upstream definition:
18:21:19 server s61705cnt72.sc.couchbase.com:4984;
18:21:19 server s61706cnt72.sc.couchbase.com:4984;
18:21:19
18:21:19 Running playbook: libraries/provision/ansible/playbooks/install-nginx.yml
18:21:19
18:21:19 PLAY [load_balancers] **********************************************************
18:21:19 skipping: no hosts matched
18:21:19
18:21:19 PLAY RECAP *********************************************************************
18:21:19
18:21:19 >>> Done provisioning cluster...
18:21:19 + '[' false == true ']'
18:21:19 + '[' Sgload == Gateload ']'
18:21:19 + '[' Sgload == Sgload ']'
18:21:19 + USE_LOADGENERATOR_PARAM=--use-sgload
18:21:19 + '[' true == true ']'
18:21:19 + RESET_SYNC_GATEWAY_PARAM=--reset-sync-gw
18:21:19 + '[' false == true ']'
18:21:19 + '[' Sgload == Gateload ']'
18:21:19 + python testsuites/syncgateway/performance/run_sgload_perf_test.py gateload --createreaders --createwriters --numreaders 10 --numupdaters 10 --numwriters 10 --numrevsperdoc 2 --numdocs 100 --numchannels 10
18:21:19 known_args: Namespace(skip_build_sgload=False)
18:21:19 sgload_args: ['gateload', '--createreaders', '--createwriters', '--numreaders', '10', '--numupdaters', '10', '--numwriters', '10', '--numrevsperdoc', '2', '--numdocs', '100', '--numchannels', '10']
18:21:19 sgload_args w/ sg url: ['gateload', '--createreaders', '--createwriters', '--numreaders', '10', '--numupdaters', '10', '--numwriters', '10', '--numrevsperdoc', '2', '--numdocs', '100', '--numchannels', '10', '--sg-url', 'http://s61705cnt72.sc.couchbase.com:4984/db/']
18:21:19 Running perf test against cluster: resources/cluster_configs/2sg_2ac_3cbs_2lgs
18:21:19 Running playbook: libraries/provision/ansible/playbooks/build-sgload.yml
18:21:19
18:21:19 PLAY [load_generators] *********************************************************
18:21:19
18:21:19 TASK [setup] *******************************************************************
18:21:21 ok: [lg2]
18:21:23 ok: [lg1]
18:21:23
18:21:23 TASK [SGLOAD | go get sgload] **************************************************
18:21:43 changed: [lg2]
18:21:45 changed: [lg1]
18:21:45
18:21:45 TASK [SGLOAD | Symlink sgload into /usr/local/bin] *****************************
18:21:45 ok: [lg2]
18:21:45 ok: [lg1]
18:21:45
18:21:45 TASK [SGLOAD | Sysctl file to increase available port range for outgoing socket connections] ***
18:21:45 ok: [lg2]
18:21:45 ok: [lg1]
18:21:45
18:21:45 TASK [SGLOAD | Shell cmd to increase available port range for outgoing socket connections] ***
18:21:46 changed: [lg2]
18:21:46 changed: [lg1]
18:21:46
18:21:46 PLAY RECAP *********************************************************************
18:21:46 lg1                        : ok=5    changed=2    unreachable=0    failed=0
18:21:46 lg2                        : ok=5    changed=2    unreachable=0    failed=0
18:21:46
18:21:46 ERROR:paramiko.transport:Unknown exception: Invalid requirement, parse error at "''"
18:21:46 ERROR:paramiko.transport:Traceback (most recent call last):
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/paramiko/transport.py", line 1774, in run
18:21:46 ERROR:paramiko.transport:    self.kex_engine.parse_next(ptype, m)
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/paramiko/kex_group1.py", line 75, in parse_next
18:21:46 ERROR:paramiko.transport:    return self._parse_kexdh_reply(m)
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/paramiko/kex_group1.py", line 111, in _parse_kexdh_reply
18:21:46 ERROR:paramiko.transport:    self.transport._verify_key(host_key, sig)
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/paramiko/transport.py", line 1619, in _verify_key
18:21:46 ERROR:paramiko.transport:    key = self._key_info[self.host_key_type](Message(host_key))
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/paramiko/rsakey.py", line 58, in __init__
18:21:46 ERROR:paramiko.transport:    ).public_key(default_backend())
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
18:21:46 ERROR:paramiko.transport:    _default_backend = MultiBackend(_available_backends())
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
18:21:46 ERROR:paramiko.transport:    "cryptography.backends"
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 733, in iter_entry_points
18:21:46 ERROR:paramiko.transport:    entries = dist.get_entry_map(group)
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2612, in get_entry_map
18:21:46 ERROR:paramiko.transport:    self._get_metadata('entry_points.txt'), self
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2350, in parse_map
18:21:46 ERROR:paramiko.transport:    maps[group] = cls.parse_group(group, lines, dist)
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2328, in parse_group
18:21:46 ERROR:paramiko.transport:    ep = cls.parse(line, dist)
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2310, in parse
18:21:46 ERROR:paramiko.transport:    return cls(res['name'], res['module'], attrs, extras, dist)
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2237, in __init__
18:21:46 ERROR:paramiko.transport:    self.extras = Requirement.parse(("x[%s]" % ','.join(extras))).extras
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2894, in parse
18:21:46 ERROR:paramiko.transport:    req, = parse_requirements(s)
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2841, in parse_requirements
18:21:46 ERROR:paramiko.transport:    yield Requirement(line)
18:21:46 ERROR:paramiko.transport:  File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2851, in __init__
18:21:46 ERROR:paramiko.transport:    raise RequirementParseError(str(e))
18:21:46 ERROR:paramiko.transport:RequirementParseError: Invalid requirement, parse error at "''"
18:21:46 ERROR:paramiko.transport:
18:21:46 ERROR:root:Exception calling execute_sgload: Invalid requirement, parse error at "''"
18:21:46 ERROR:root:Traceback (most recent call last):
18:21:46   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 63, in execute_sgload
18:21:46     ssh.connect(lgs_host, username=constants.DEFAULT_REMOTE_USER)  # TODO!! get this from ansible.cfg
18:21:46   File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/paramiko/client.py", line 338, in connect
18:21:46     t.start_client()
18:21:46   File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/paramiko/transport.py", line 493, in start_client
18:21:46     raise e
18:21:46 RequirementParseError: Invalid requirement, parse error at "''"
18:21:46
18:21:50 SSH connection to s61904cnt72.sc.couchbase.com
18:21:50 SSH connection to s61905cnt72.sc.couchbase.com
18:21:50 Exception calling execute_sgload: Invalid requirement, parse error at "''"
18:21:50 Traceback (most recent call last):
18:21:50   File "testsuites/syncgateway/performance/run_sgload_perf_test.py", line 63, in execute_sgload
18:21:50     ssh.connect(lgs_host, username=constants.DEFAULT_REMOTE_USER)  # TODO!! get this from ansible.cfg
18:21:50   File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/paramiko/client.py", line 338, in connect
18:21:50     t.start_client()
18:21:50   File "/var/jenkins/workspace/sync-gateway-perf-test/venv/lib/python2.7/site-packages/paramiko/transport.py", line 493, in start_client
18:21:50     raise e
18:21:50 RequirementParseError: Invalid requirement, parse error at "''"
18:21:50

* another fix attempt for RequirementParseError: Invalid requirement, parse error at

* Instead of setting perf cluster hostnames at the OS level, just set them in telgraf agent config

* Assign lg hosts to sg hosts with random distribution

* Move  Install + configure telegraf out of install_deps and into run_perf_test

* Uncommented percentiles geenration for statsd timers

* Enable gateload statsd output in the gateload config file

* Added Grafana perf dashboard so that it may be impoeted into local grafana instances for local testing

* Fix some pylint warnings

* Fix more pylint errros

* Remove dead code

* Was previously ignoring lg2sg

* Kill any sgload instances before building

* Revert "Kill any sgload instances before building"

This reverts commit 39cf6e70929c9f8727f775c7ad5606d6b6ef6650.

* Only run sgload on one single load generator

* Stream the sgload output to the console to see what’s going on

Trying to figure out why this job is completely stuck

* Add telegraf config and install for "sg_accels" host group

* Update comment