Support 4.7 cb in install-couchbase-server-package.yml (#836)
* fix configure cluster settings for 4.7 version

ERROR: argument --cluster-username is required

* typo fix in install-couchbase-server-package.yml

* one more fix in install-couchbase-server-package.yml

* use --user instead of --username in install-couchbase-server-package.yml

* support 4.7.X and up in install-couchbase-server-package